# Generated by Django 2.2.6 on 2019-10-12 10:46

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
                ('need', models.TextField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
