# Generated by Django 2.2.5 on 2019-10-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='victims',
            table='Victims',
        ),
    ]
