# Generated by Django 2.1.13 on 2019-10-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0003_auto_20191012_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('sub_type', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Needs',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('requirement', models.ForeignKey(db_column='Need_id', on_delete=django.db.models.deletion.CASCADE, to='victims.Needs')),
            ],
        ),
        migrations.CreateModel(
            name='SafeLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'SafeLocations',
            },
        ),
        migrations.RemoveField(
            model_name='victims',
            name='need',
        ),
        migrations.AddField(
            model_name='victims',
            name='requirement_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='victims',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='victims',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterModelTable(
            name='victims',
            table='Victims',
        ),
        migrations.AddField(
            model_name='requirements',
            name='victim_id',
            field=models.ForeignKey(db_column='Victim_id', on_delete=django.db.models.deletion.CASCADE, to='victims.Victims'),
        ),
    ]
