# Generated by Django 2.2.5 on 2019-10-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0004_auto_20191012_1844'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requirements',
            table='Requirements',
        ),
    ]
