# Generated by Django 2.1.13 on 2019-10-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0005_auto_20191012_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='sub_type',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
