# Generated by Django 2.1.13 on 2019-10-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0006_auto_20191012_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='sub_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
