# Generated by Django 2.2.5 on 2019-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0006_auto_20191012_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
