# Generated by Django 2.1.13 on 2019-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0007_auto_20191012_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='sub_type',
            field=models.CharField(default=True, max_length=60, null=True),
        ),
    ]
