# Generated by Django 2.2.6 on 2019-10-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0008_auto_20191013_0013'),
        ('victims', '0008_auto_20191012_2001'),
    ]

    operations = [
    ]
