# Generated by Django 2.2.5 on 2019-10-13 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20191012_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='need',
            field=models.ForeignKey(db_column='Need_id', on_delete=django.db.models.deletion.CASCADE, to='victims.Needs'),
        ),
        migrations.AlterModelTable(
            name='volunteer_supplier_victim',
            table='Volunteer_Supplier_Victim',
        ),
    ]
