# Generated by Django 2.2.6 on 2019-10-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_auto_20191012_2036'),
        ('volunteers', '0005_auto_20191013_0013'),
    ]

    operations = [
    ]
