# Generated by Django 2.2.5 on 2019-10-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_auto_20191013_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteers',
            name='need',
        ),
    ]
