# Generated by Django 2.2.6 on 2019-10-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_merge_20191013_0122'),
        ('volunteers', '0006_remove_volunteers_need'),
    ]

    operations = [
    ]
