insert into `locations` (location_name) values ('Adambakkam');
insert into `locations` (location_name) values ('Adyar');
insert into `locations` (location_name) values ('Alandur');
insert into `locations` (location_name) values ('Anna Nagar');
insert into `locations` (location_name) values ('Ashok Nagar');
insert into `locations` (location_name) values ('Ayanavaram');
insert into `locations` (location_name) values ('Chennai');
insert into `locations` (location_name) values ('Chetpet');
insert into `locations` (location_name) values ('Chitlapakkam');
insert into `locations` (location_name) values ('Choolai');
insert into `locations` (location_name) values ('Chromepet');
insert into `locations` (location_name) values ('Egmore');
insert into `locations` (location_name) values ('Gopalapuram');
insert into `locations` (location_name) values ('Guindy');
insert into `locations` (location_name) values ('Injambakkam');
insert into `locations` (location_name) values ('K. K. Nagar');
insert into `locations` (location_name) values ('Kodambakkam');
insert into `locations` (location_name) values ('Kodungaiyur');
insert into `locations` (location_name) values ('Kolathur');
insert into `locations` (location_name) values ('Korukkupet');
insert into `locations` (location_name) values ('Madhavaram');
insert into `locations` (location_name) values ('Mambalam');
insert into `locations` (location_name) values ('Mannivakkam');
insert into `locations` (location_name) values ('Medavakkam');
insert into `locations` (location_name) values ('Meenambakkam');
insert into `locations` (location_name) values ('Mudichur');
insert into `locations` (location_name) values ('Mylapore');
insert into `locations` (location_name) values ('New Washermenpet');
insert into `locations` (location_name) values ('Nungambakkam');
insert into `locations` (location_name) values ('Park Town');
insert into `locations` (location_name) values ('Peerkankaranai');
insert into `locations` (location_name) values ('Perambur');
insert into `locations` (location_name) values ('Perungalathur');
insert into `locations` (location_name) values ('Purasawalkam');
insert into `locations` (location_name) values ('Saidapet');
insert into `locations` (location_name) values ('Sembakkam');
insert into `locations` (location_name) values ('Shenoy Nagar');
insert into `locations` (location_name) values ('Sholinganallur');
insert into `locations` (location_name) values ('T. Nagar');
insert into `locations` (location_name) values ('Teynampet');
insert into `locations` (location_name) values ('Tharamani');
insert into `locations` (location_name) values ('Thiru. Vi. Ka Nagar');
insert into `locations` (location_name) values ('Thuraipakkam');
insert into `locations` (location_name) values ('Tirusulam');
insert into `locations` (location_name) values ('Tondiarpet');
insert into `locations` (location_name) values ('Triplicane');
insert into `locations` (location_name) values ('Vadapalani');
insert into `locations` (location_name) values ('Vandalur');
insert into `locations` (location_name) values ('Vyasarpadi');
insert into `locations` (location_name) values ('Washermanpet');