# Generated by Django 2.1.13 on 2019-10-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20191012_1233'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suppliers',
            table=None,
        ),
    ]
