# Generated by Django 2.2.5 on 2019-10-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_suppliers_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
